stages:
    - build1
    - build2
odin_http:
    stage: build1
    only:
        - /^master/i
        - /^feature/i
        - tags
        - /^develop/i
    script:
        - docker build --network=host --tag "${DOCKER_REGISTRY_ADDRESS}/odin-http" ./src/odin-http
        - docker login --username "${DOCKER_REGISTRY_USER}" --password "${DOCKER_REGISTRY_PASSWORD}" "${DOCKER_REGISTRY_ADDRESS}"
        - docker image push "${DOCKER_REGISTRY_ADDRESS}/odin-http"
    tags:
        - centos7-2
odin_ml:
    stage: build2
    only:
        - /^master/i
        - /^feature/i
        - tags
        - /^develop/i
    script:
        - docker build --network=host --tag "${DOCKER_REGISTRY_ADDRESS}/odin-ml" ./src/odin
        - docker login --username "${DOCKER_REGISTRY_USER}" --password "${DOCKER_REGISTRY_PASSWORD}" "${DOCKER_REGISTRY_ADDRESS}"
        - docker image push "${DOCKER_REGISTRY_ADDRESS}/odin-ml"
    tags:
        - centos7-2
