# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ConfigDefinition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, content: str=None):  # noqa: E501
        """ConfigDefinition - a model defined in Swagger

        :param id: The id of this ConfigDefinition.  # noqa: E501
        :type id: str
        :param name: The name of this ConfigDefinition.  # noqa: E501
        :type name: str
        :param content: The content of this ConfigDefinition.  # noqa: E501
        :type content: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'content': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'content': 'content'
        }
        self._id = id
        self._name = name
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfigDefinition of this ConfigDefinition.  # noqa: E501
        :rtype: ConfigDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ConfigDefinition.


        :return: The id of this ConfigDefinition.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ConfigDefinition.


        :param id: The id of this ConfigDefinition.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ConfigDefinition.


        :return: The name of this ConfigDefinition.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ConfigDefinition.


        :param name: The name of this ConfigDefinition.
        :type name: str
        """

        self._name = name

    @property
    def content(self) -> str:
        """Gets the content of this ConfigDefinition.


        :return: The content of this ConfigDefinition.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this ConfigDefinition.


        :param content: The content of this ConfigDefinition.
        :type content: str
        """

        self._content = content
