# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.job_definition import JobDefinition  # noqa: F401,E501
from swagger_server import util


class JobWrapperDefinition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, job: JobDefinition=None):  # noqa: E501
        """JobWrapperDefinition - a model defined in Swagger

        :param job: The job of this JobWrapperDefinition.  # noqa: E501
        :type job: JobDefinition
        """
        self.swagger_types = {
            'job': JobDefinition
        }

        self.attribute_map = {
            'job': 'job'
        }
        self._job = job

    @classmethod
    def from_dict(cls, dikt) -> 'JobWrapperDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobWrapperDefinition of this JobWrapperDefinition.  # noqa: E501
        :rtype: JobWrapperDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job(self) -> JobDefinition:
        """Gets the job of this JobWrapperDefinition.


        :return: The job of this JobWrapperDefinition.
        :rtype: JobDefinition
        """
        return self._job

    @job.setter
    def job(self, job: JobDefinition):
        """Sets the job of this JobWrapperDefinition.


        :param job: The job of this JobWrapperDefinition.
        :type job: JobDefinition
        """

        self._job = job
