# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.pipeline_definition import PipelineDefinition  # noqa: F401,E501
from swagger_server import util


class PipelineWrapperDefinition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pipeline: PipelineDefinition=None):  # noqa: E501
        """PipelineWrapperDefinition - a model defined in Swagger

        :param pipeline: The pipeline of this PipelineWrapperDefinition.  # noqa: E501
        :type pipeline: PipelineDefinition
        """
        self.swagger_types = {
            'pipeline': PipelineDefinition
        }

        self.attribute_map = {
            'pipeline': 'pipeline'
        }
        self._pipeline = pipeline

    @classmethod
    def from_dict(cls, dikt) -> 'PipelineWrapperDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PipelineWrapperDefinition of this PipelineWrapperDefinition.  # noqa: E501
        :rtype: PipelineWrapperDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pipeline(self) -> PipelineDefinition:
        """Gets the pipeline of this PipelineWrapperDefinition.


        :return: The pipeline of this PipelineWrapperDefinition.
        :rtype: PipelineDefinition
        """
        return self._pipeline

    @pipeline.setter
    def pipeline(self, pipeline: PipelineDefinition):
        """Sets the pipeline of this PipelineWrapperDefinition.


        :param pipeline: The pipeline of this PipelineWrapperDefinition.
        :type pipeline: PipelineDefinition
        """

        self._pipeline = pipeline
