# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UploadDefinition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, bytes: int=None, location: str=None):  # noqa: E501
        """UploadDefinition - a model defined in Swagger

        :param bytes: The bytes of this UploadDefinition.  # noqa: E501
        :type bytes: int
        :param location: The location of this UploadDefinition.  # noqa: E501
        :type location: str
        """
        self.swagger_types = {
            'bytes': int,
            'location': str
        }

        self.attribute_map = {
            'bytes': 'bytes',
            'location': 'location'
        }
        self._bytes = bytes
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'UploadDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UploadDefinition of this UploadDefinition.  # noqa: E501
        :rtype: UploadDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bytes(self) -> int:
        """Gets the bytes of this UploadDefinition.


        :return: The bytes of this UploadDefinition.
        :rtype: int
        """
        return self._bytes

    @bytes.setter
    def bytes(self, bytes: int):
        """Sets the bytes of this UploadDefinition.


        :param bytes: The bytes of this UploadDefinition.
        :type bytes: int
        """

        self._bytes = bytes

    @property
    def location(self) -> str:
        """Gets the location of this UploadDefinition.


        :return: The location of this UploadDefinition.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this UploadDefinition.


        :param location: The location of this UploadDefinition.
        :type location: str
        """

        self._location = location
