# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_definition import UserDefinition  # noqa: F401,E501
from swagger_server import util


class UserWrapperDefinition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: UserDefinition=None):  # noqa: E501
        """UserWrapperDefinition - a model defined in Swagger

        :param user: The user of this UserWrapperDefinition.  # noqa: E501
        :type user: UserWrapperDefinition
        """
        self.swagger_types = {
            'user': UserDefinition
        }

        self.attribute_map = {
            'user': 'user'
        }
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'UserDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserDefinition of this UserDefinition.  # noqa: E501
        :rtype: UserWrapperDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> UserDefinition:
        """Gets the user of this UserDefinition.


        :return: The user of this UserDefinition.
        :rtype: UserWrapperDefinition
        """
        return self._user

    @user.setter
    def user(self, user: UserDefinition):
        """Sets the user of this UserDefinition.


        :param user: The user of this UserDefinition.
        :type user: UserDefinition
        """

        self._user = user
