# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VolumeMountDefinition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, path: str=None, name: str=None, claim: str=None):  # noqa: E501
        """VolumeMountDefinition - a model defined in Swagger

        :param path: The path of this VolumeMountDefinition.  # noqa: E501
        :type path: str
        :param name: The name of this VolumeMountDefinition.  # noqa: E501
        :type name: str
        :param claim: The claim of this VolumeMountDefinition.  # noqa: E501
        :type claim: str
        """
        self.swagger_types = {
            'path': str,
            'name': str,
            'claim': str
        }

        self.attribute_map = {
            'path': 'path',
            'name': 'name',
            'claim': 'claim'
        }
        self._path = path
        self._name = name
        self._claim = claim

    @classmethod
    def from_dict(cls, dikt) -> 'VolumeMountDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VolumeMountDefinition of this VolumeMountDefinition.  # noqa: E501
        :rtype: VolumeMountDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self) -> str:
        """Gets the path of this VolumeMountDefinition.


        :return: The path of this VolumeMountDefinition.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this VolumeMountDefinition.


        :param path: The path of this VolumeMountDefinition.
        :type path: str
        """

        self._path = path

    @property
    def name(self) -> str:
        """Gets the name of this VolumeMountDefinition.


        :return: The name of this VolumeMountDefinition.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VolumeMountDefinition.


        :param name: The name of this VolumeMountDefinition.
        :type name: str
        """

        self._name = name

    @property
    def claim(self) -> str:
        """Gets the claim of this VolumeMountDefinition.


        :return: The claim of this VolumeMountDefinition.
        :rtype: str
        """
        return self._claim

    @claim.setter
    def claim(self, claim: str):
        """Sets the claim of this VolumeMountDefinition.


        :param claim: The claim of this VolumeMountDefinition.
        :type claim: str
        """

        self._claim = claim
