# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from midgard.server.models.base_model_ import Model
from midgard.server import util


class GPUMaxClockInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sm_clock: float=None, unit: str=None):  # noqa: E501
        """GPUMaxClockInfo - a model defined in Swagger

        :param sm_clock: The sm_clock of this GPUMaxClockInfo.  # noqa: E501
        :type sm_clock: float
        :param unit: The unit of this GPUMaxClockInfo.  # noqa: E501
        :type unit: str
        """
        self.swagger_types = {
            'sm_clock': float,
            'unit': str
        }

        self.attribute_map = {
            'sm_clock': 'smClock',
            'unit': 'unit'
        }
        self._sm_clock = sm_clock
        self._unit = unit

    @classmethod
    def from_dict(cls, dikt) -> 'GPUMaxClockInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GPUMaxClockInfo of this GPUMaxClockInfo.  # noqa: E501
        :rtype: GPUMaxClockInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sm_clock(self) -> float:
        """Gets the sm_clock of this GPUMaxClockInfo.


        :return: The sm_clock of this GPUMaxClockInfo.
        :rtype: float
        """
        return self._sm_clock

    @sm_clock.setter
    def sm_clock(self, sm_clock: float):
        """Sets the sm_clock of this GPUMaxClockInfo.


        :param sm_clock: The sm_clock of this GPUMaxClockInfo.
        :type sm_clock: float
        """

        self._sm_clock = sm_clock

    @property
    def unit(self) -> str:
        """Gets the unit of this GPUMaxClockInfo.


        :return: The unit of this GPUMaxClockInfo.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this GPUMaxClockInfo.


        :param unit: The unit of this GPUMaxClockInfo.
        :type unit: str
        """

        self._unit = unit
