# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from midgard.server.models.base_model_ import Model
from midgard.server.models.gpu_device_info import GPUDeviceInfo  # noqa: F401,E501
from midgard.server import util


class GPUDeviceWrapperDefinition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, gpu: GPUDeviceInfo=None):  # noqa: E501
        """GPUDeviceWrapperDefinition - a model defined in Swagger

        :param gpu: The gpu of this GPUDeviceWrapperDefinition.  # noqa: E501
        :type gpu: GPUDeviceInfo
        """
        self.swagger_types = {
            'gpu': GPUDeviceInfo
        }

        self.attribute_map = {
            'gpu': 'gpu'
        }
        self._gpu = gpu

    @classmethod
    def from_dict(cls, dikt) -> 'GPUDeviceWrapperDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GPUDeviceWrapperDefinition of this GPUDeviceWrapperDefinition.  # noqa: E501
        :rtype: GPUDeviceWrapperDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def gpu(self) -> GPUDeviceInfo:
        """Gets the gpu of this GPUDeviceWrapperDefinition.


        :return: The gpu of this GPUDeviceWrapperDefinition.
        :rtype: GPUDeviceInfo
        """
        return self._gpu

    @gpu.setter
    def gpu(self, gpu: GPUDeviceInfo):
        """Sets the gpu of this GPUDeviceWrapperDefinition.


        :param gpu: The gpu of this GPUDeviceWrapperDefinition.
        :type gpu: GPUDeviceInfo
        """

        self._gpu = gpu
